### ISSUE TITLE
Attribute duplicate song to original post user

### ISSUE THREAD

**Issue by mitchheard** [louhow/slackbot-fun#1]
User Story:
As a song poster, I want to see who originally posted a song I just duplicate posted, so that I can give them mad props.

From Kevmar:
"I think this is already on the scrum board, but if i post a Spotify link of a song on the thread that i am jamming like "damn, this song is good" and i post it here, it could tell me who was original poster so i could give props"

Acceptance Criteria:
- If a song is posted in #music that has already been posted, provide the dupe message + the user who originally posted it
- If a song is posted in a thread within #music that has already been posted, provide the dupe message + user who originally posted it (this is dependent on another issue)
- give an @<user> to the user who posted it, so they can make sure they see the mad props

**Comment by louhow** [comment]
Fixed!
